### ISSUE TITLE
Getting errorq

### ISSUE THREAD

**Issue by nazgul6** [LeonardoCardoso/gsrd#1]
Hi,

does this still work?

I'm getting the following in terminal:

```
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Library/Ruby/Gems/2.3.0/gems/gsrd-0.1.6/bin/gsrd:3:in `<top (required)>'
> 	from /usr/local/bin/gsrd:22:in `load'
> 	from /usr/local/bin/gsrd:22:in `<main>'
```

**Comment by leonardocardoso** [comment]
It seems you don't have bundler installed.
Please try `gem install bundler` and then run my lib.
If it doesn't work, let me know.
